### ISSUE TITLE
Utiliser le plugin

### ISSUE THREAD

**Issue by Airwolf33** [kavod/kring#4]
Bonjour Kavod, 
comment utiliser ton plugin qui me plait fortement pour la gestion de l'alarme Ring par Jeedom ?
Dans le market il est privé et donc impossible de l'installer...=
Merci de ton aide.

**Comment by kavod** [comment]
Bonjour Airwolf33,

Tu peux installer le plugin manuellement en passant par "Download zip" sur github (voici le [lien direct](https://github.com/kavod/kring/archive/refs/heads/main.zip)). Une fois le fichier ZIP téléchargé, il faut que tu actives l'ajout de plugin par fichiers (Système > Configuration > Mise à jour/Market > Configuration des dépôts > Fichier) afin de pouvoir l'ajouter manuellement via Plugins > Gestion des plugins > + Plugins > Type de source = Fichier > ID logique du plugin = "kring" et de charger le fichier Zip.

Je laisse pour le moment le plugin en privé sur le market Jeedom car je considère qu'il n'est pas encore assez finalisé pour être distribué. Je manque un peu de temps en ce moment pour le terminer. 
Malgré tout, n'hésite pas à me faire tes retours sur Github afin que je puisse les prendre en compte lorsque je m'y remettrai.

Merci
